# Earth geometry
EARTH_DEGREE_KM = 111.0

# Redis and Caching
QR_CODE_EXPIRY_SECONDS = 86500 
CACHE_TIMEOUT_SECONDS = 3600
REDIS_SOCKET_TIMEOUT = 5
REDIS_CONNECT_TIMEOUT = 5
LIMITER_CONNECT_TIMEOUT = 30

# QR Code generation
QR_BOX_SIZE = 10
QR_BORDER_SIZE = 1

# User constraints
DEFAULT_REROLLS = 2
VOUCHER_EXPIRY_HOURS = 48

# Database constraints
MAX_STRING_LENGTH = 255
SHORT_STRING_LENGTH = 50
CATEGORY_STRING_LENGTH = 25
TOKEN_LENGTH = 36
LATITUDE_MIN = -90
LATITUDE_MAX = 90
LONGITUDE_MIN = -180
LONGITUDE_MAX = 180

# Rate limits
RATE_LIMIT_STANDARD = "10 per minute; 100 per day"
RATE_LIMIT_AUTOCOMPLETE = "45 per minute"
RATE_LIMIT_AUTOCOMPLETE_DAILY = "190 per 24 hours"
RATE_LIMIT_PLACE_DETAILS = "15 per 24 hours"

# HTTP Status Codes
HTTP_400_BAD_REQUEST = 400
HTTP_404_NOT_FOUND = 404
HTTP_429_TOO_MANY_REQUESTS = 429
HTTP_500_INTERNAL_SERVER_ERROR = 500
